<?xml version="1.0"?>
<package format="3">
  <name>hazard_inspection_description</name>
  <version>0.1.0</version>

  <description>
    Robot description and Gazebo simulation resources for the autonomous hazardous-environment inspection robot.
  </description>

  <maintainer email="shahamdan668@gmail.com">Sohaib</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>
  <depend>gazebo_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
